name: Build frontend

on:
  push:
    paths:
      ["src/WebUI/WebApp/clientapp/**", ".github/workflows/frontend-build.yaml"]
  pull_request:
    paths:
      ["src/WebUI/WebApp/clientapp/**", ".github/workflows/frontend-build.yaml"]

defaults:
  run:
    working-directory: src/WebUI/WebApp/clientapp

jobs:
  build:
    runs-on: ubuntu-latest
    # Build master branch for Govmeeting owner. Build all but master for the forks.
    # The purpose of this setting is to cut down on unnecesary workflow builds.
    # Normally (or at least in my case) the developer pushes changes to their fork on branches other than master.
    # These should be checked by the workflow.
    # But when the developer pushes the master branch, it is usually just an update of the master branch
    # that they fetched from upstream, which needn't be checked.
    if: (github.repository_owner == 'Govmeeting' && github.ref == 'refs/heads/master') || (github.repository_owner != 'Govmeeting' && github.ref != 'refs/heads/master')

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean Install
        run: npm ci

      - name: Prettier & Format checks
        run: npm run ci:format

      - name: Unit Tests
        run: npm run ci:test

      - name: Clean Build
        run: npm run ci:build

      - name: Cypress Tests
        run: npm run ci:cypress

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: src/WebUI/WebApp/clientapp/dist # The folder the action should deploy.
